### ISSUE TITLE
Only works in discord.py 1.7.x

### ISSUE THREAD

**Issue by BadUserHater** [MDiscordDev/slashcmds.py#3]
Hello. I have noticed that with this way of adding slash commands to your discord.py, this method only works in discord.py 1.7.x

I will let you know if I find a way for discord.py 2.0 but for now, edit the requirements file or message in the README that this way only work in discord.py 1.7.x

**Comment by BadUserHater** [comment]
I figured out how to do this in discord.py 2.0 without the use of cogs. Also shows you can have those "Only you can see these" messages:

from discord.ext import commands

@client.tree.command(name="ping", description='Checks the Latency of the Bot')
async def ping(interaction: discord.Interaction):
    await interaction.response.send_message("PONG!\nLatency: {round(client.latency * 1000)}ms", ephemeral=True)

**Comment by BadUserHater** [comment]
Hello. I found a way to make it work in discord.py 2.0 so you can make a seperate file for this. The old version is only for Discord.py 1.7.x and does not work in discord.py 2.0

``py
import discord
from discord.ext import commands
import aiohttp
from contextlib import redirect_stdout

intents = discord.Intents.default()
intents.members = True
intents.message_content = True
client = commands.Bot(command_prefix= commands.when_mentioned_or('!'), intents=intents)
client.remove_command("help")

@client.event
async def on_ready():
    await client.change_presence(activity=discord.Activity(type=discord.ActivityType.watching, name=f"myself be one with the bin"))
    print("BOT IS ONLINE")
    try:
        synced = await client.tree.sync()
        print(f"{len(synced)} Slash Commands successfully Synced")
    except Exception as e:
        print(e)

@client.command()
async def ping(ctx):
    await ctx.send(f'PONG!\nLatency: {round(client.latency * 1000)}ms')

@client.tree.command(name="ping", description='Checks the Latency of the Bot')
async def ping(interaction: discord.Interaction):
    await interaction.response.send_message("PONG!\nLatency: {round(client.latency * 1000)}ms", ephemeral=True)

client.run("BOTTOKENHERE")

**Comment by MDiscordDev** [comment]
Thank you for bringing this to my attention. I have now updated the repo so 1 file is for discord.py 1.7.x and the other file which here is for discord.py 2.0

Again, thank you for bringing this to my attention. I am now closing this.
